import styles from '@/styles/Home.module.css'
import { Button, useTheme } from '@acid-info/lsd-react'
import styled from '@emotion/styled'
import Head from 'next/head'

const StyledButton = styled(Button)`
  &.${Button.classes.disabled} {
  }
`

export default function Home() {
  const theme = useTheme()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ marginBottom: 50 }}>
          <Button disabled>Simple Button</Button>
          <div
            style={{
              width: 1000,
              marginTop: 50,
              display: 'flex',
              flexDirection: 'column',
              rowGap: 12,
              alignItems: 'flex-start',
            }}
          >
            <StyledButton size="small" disabled>
              Button
            </StyledButton>
            <StyledButton disabled size="medium">
              Button
            </StyledButton>
            <StyledButton disabled size="large">
              Button
            </StyledButton>

            <StyledButton size="small">Button</StyledButton>
            <StyledButton size="medium">Button</StyledButton>
            <StyledButton size="large">Button</StyledButton>
          </div>
        </div>
        <pre>
          <code>{theme.globalStyles.styles}</code>
        </pre>
        <style></style>
      </main>
    </>
  )
}
